### ISSUE TITLE
Connect Mute key to TotalMix Dim

### ISSUE THREAD

**Issue by alexhayes** [fgimian/totalmix-volume-control#1]
Firstly, thanks so much for making this! I attempted something similar in purpose using AHK (using OSC also), which worked but this is so much better.

I was wondering if you had plans to connect up the Mute key to TotalMix's Dim function?

If not, would you be open to a pull request that implements this?

**Comment by fgimian** [comment]
Thanks for the suggestion @alexhayes, seems like a good idea.  I'll consider it when I have some time to work on the next release. 😄

**Comment by fgimian** [comment]
I'll be adding some notes here as I work through this.  I can't quite promise any sort of timeline at this stage but I do like the idea so will be working through it slowly in the background.

Dim can be set via the following OSC messages:

# Enable Dim

**Address**: `/1/mainDim`
**Value**: `1`

# Disable Dim

**Address**: `/1/mainDim`
**Value**: `0`

**Comment by fgimian** [comment]
This is now in the works and will be coming soon! 😄

**Comment by fgimian** [comment]
Hey mate, please try out the [latest build](https://artprodeau1.artifacts.visualstudio.com/A90b9ff6d-c63f-424f-b295-04ca46dc7b32/16665519-5043-40d6-a8dd-9d2c71236dd6/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2ZnaW1pYW4vcHJvamVjdElkLzE2NjY1NTE5LTUwNDMtNDBkNi1hOGRkLTlkMmM3MTIzNmRkNi9idWlsZElkLzcxL2FydGlmYWN0TmFtZS9Kb2I1/content?format=file&subPath=%2Fa%2FTotalMixVCSetup-v0.3.1%2B6-Release-Installer.exe) which now has dim functionality built in (hooked up to the mute key on your keyboard).  It also adds plain text tray tooltips for Windows 11 users.

I'll be testing this on my system over the next day and releasing v0.4.0 tomorrow evening if no major issues are found.

Merry Christmas!! 🎅 
Fotis

**Comment by fgimian** [comment]
A new version v0.4.0 is now out with this functionality, so I'll close this issue. 😄 

Cheers
Fotis
