### ISSUE TITLE
Doesn't work if you start the app with ProtonVPN open

### ISSUE THREAD

**Issue by be5invis** [fgimian/totalmix-volume-control#4]
Reproduction:

 1. Connect a VPN through ProtonVPN.
 2. Start TVC.
 3. It fails to connect.

I tried to add TVC to ProtonVPN's exclude apps list but it doesn't fix the problem. Other VPNs may also reproduce.

**Comment by fgimian** [comment]
Ultimately, the application will attempt to communicate with your RME device via the UDP hostname and port configured. If the VPN interrupts this ability, I'm afraid there's not much that can be done from my end.

Being on a VPN typically affects the entire network stack and can change visibility of local resources. Unless you can add an exclusion to this, there may be no way around this.

Perhaps you could try [Nix](https://bsound.co.nz/tools-nix) which does a similar task to my program to see if it works.

Cheers
Fotis

**Comment by fgimian** [comment]
I think it's safe to close this now, if you find that Nix works better for you, f eel free to go with t hat, although I suspect it'll have the same problem on a VPN as any app trying to communicate to local resources over UDP.

Cheers
Fotis
